### ISSUE TITLE
Error: WRITE_TOO_BIG

### ISSUE THREAD

**Issue by Hbombre** [FirebaseExtended/firebase-import#46]
Error: WRITE_TOO_BIG: Data to write exceeds the maximum size that can be modified with a single request.

Json size is 291.8 MB

**Comment by mikelehen** [comment]
That's strange...  The script is supposed to break up the file into chunks less than 1MB (https://github.com/FirebaseExtended/firebase-import/blob/8e071f440a01a866f8dad806011973c1c63aaca2/src/firebase-import.js#L13) which should avoid that error.

This script is old and not very actively supported, but if you can figure out how that logic is breaking we may be able to make a fix...

**Comment by Hbombre** [comment]
The json consists of almost 1.3 million records. The funny thing is is that I uploaded it fine once, then realized one field was an int instead of string, made the change, and that must have tipped the scale.

**Comment by mikelehen** [comment]
The size / number of records shouldn't really matter.  firebase-import splits the file into many small chunks and uploads them one at a time.  It's specifically designed to avoid WRITE_TOO_BIG errors, regardless of the JSON size.

**Comment by Hbombre** [comment]
Error: WRITE_TOO_BIG: Data to write exceeds the maximum size that can be modified with a single request.

Would it me something on the Firebase side?

**Comment by mikelehen** [comment]
Not sure what you're asking.  That error comes from the Firebase side, but the script is designed to avoid it.  So if you're seeing the error, it probably means there's a bug in the script.

To try to debug you could add logging to the script [here](https://github.com/FirebaseExtended/firebase-import/blob/8e071f440a01a866f8dad806011973c1c63aaca2/src/firebase-import.js#L149) to log the chunks and see which one is the biggest, etc.

**Comment by mikelehen** [comment]
Talking to somebody from the backend, I think we've figured out what's going on.  firebase-import tries to delete the existing data before writing the new data, and I think that delete is actually what's triggering the WRITE_TOO_BIG error.

As a workaround, you could use the [Firebase CLI](https://firebase.google.com/docs/cli) to delete the data with "firebase database:remove ..." before using firebase-import.

That said, you might want to try just importing the data with Firebase CLI directly.  i.e. "firebase database:set ..."  I don't know what the maximum size it supports is though.

**Comment by mikelehen** [comment]
See https://firebase.googleblog.com/2019/03/large-deletes-in-realtime-database.html for more details about large deletes...

**Comment by Hbombre** [comment]
That was the problem! I deleted with CLI and now I have it uploading again. Thank you!
